spring:
  application:
    name: valuable-one-api
  profiles:
    active: dev


# swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

# logging configuration
logging:
  level:
    root: INFO
    com.valuable: DEBUG
  file:
    name: app.log

resilience4j:
  retry:
    releaseLoanRetry:
      max-attempts: 3
      wait-duration: 10s
      retry-exceptions:
        - java.io.IOException
        - org.springframework.web.reactive.function.client.WebClientRequestException
  circuitbreaker:
    releaseLoanCircuitBreaker:
      register-health-indicator: true
      sliding-window-size: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 30s

